version: "3.9"
services:
  nyala-fe:
    container_name: nyala-fe
    hostname: nyala-fe
    build:
      context: ./nyala-fe
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7128:3000
    depends_on:
      - nyala-media-service
    networks:
      - nyala-network

  nyala-media-service:
    container_name: nyala-media-service
    build:
      context: ./nyala-media-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7890:8000
    volumes:
      - ./nyala-media-service/src/uploads:/app/src/uploads
    networks:
      - nyala-network

networks:
  nyala-network:
    driver: bridge
