import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
// import { auth } from "ln/lib/auth";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        {children}
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
