import {
  ArrowBigDownDash,
  ArrowBigUpDash,
  ArrowLeft,
  ArrowRight,
  ArrowUpFromDot,
  BadgePlus,
  ChartBarStacked,
  House,
  Images,
  LucideIcon,
  MapPinned,
  MessageCircle,
  Search,
  SendHorizonal,
  Settings,
  User,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  settings: Settings,
  house: House,
  search: Search,
  createPost: BadgePlus,
  map: MapPinned,
  user: User,
  comment: MessageCircle,
  up: ArrowBigUpDash,
  down: ArrowBigDownDash,
  share: SendHorizonal,
  back: ArrowLeft,
  next: ArrowRight,
  updot: ArrowUpFromDot,
  images: Images,
  x: X,
  category: ChartBarStacked,
};
